# Generated by Django 5.2.15 on 2026-07-03 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 3, 16, 53, 54, 305002, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
