# Generated by Django 5.2.15 on 2026-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('Action', '액션'), ('Thriller', '스릴러'), ('Romance', '로맨스'), ('Comedy', '코미디'), ('SF', '공상과학'), ('Horror', '공포'), ('Drama', '드라마'), ('Animaton', '애니메이션')], max_length=50),
        ),
    ]
